services:
  userDB:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${USERDB_PORT}:5432
    volumes:
      - ./db_data/user:/var/lib/postgresql/data

  taskDB:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${TASKDB_PORT}:5432
    volumes:
      - ./db_data/task:/var/lib/postgresql/data
