apiVersion: v1
kind: ConfigMap
metadata:
  name: task-db-config
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: task-db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-db
spec:
  selector:
    matchLabels:
      app: task-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: task-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: task-db-config
            - secretRef:
                name: task-db-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: task-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: task-db-data
          persistentVolumeClaim:
            claimName: task-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: task-db
spec:
  selector:
    app: task-db
  ports:
    - port: 5432
      targetPort: 5432
